# -*- coding: utf-8 -*-
"""Interface IISc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbbbHYLKOnuAdGNXJOKam2VE779JUqj-
"""

# # Install system dependencies
!apt-get install nodejs -y


# Install Python dependencies

!pip install ftfy regex tqdm
!pip install streamlit colabcode -q
!pip install git+https://github.com/openai/CLIP.git

from google.colab import drive
drive.mount('/content/drive')

import torch

# Then in your model code
checkpoint = torch.load("/content/drive/MyDrive/checkpoints.pt", map_location="cpu")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501